services:
  - type: web
    name: esco-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: DEEPSEEK_API_KEY
        fromSecret: true